from .gender_nl_filter import (
    NODE_CLASS_MAPPINGS as NL_CLASS_MAPPINGS,
)
from .gender_nl_filter import (
    NODE_DISPLAY_NAME_MAPPINGS as NL_DISPLAY_MAPPINGS,
)
from .gender_tag_filter import (
    NODE_CLASS_MAPPINGS as TAG_CLASS_MAPPINGS,
)
from .gender_tag_filter import (
    NODE_DISPLAY_NAME_MAPPINGS as TAG_DISPLAY_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {**TAG_CLASS_MAPPINGS, **NL_CLASS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**TAG_DISPLAY_MAPPINGS, **NL_DISPLAY_MAPPINGS}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
